export const data = [
  {
    id: 1,
    name: 'Camaro',
    details: 1970,
    quantity: 95,
    category: 'Chevrolet',
    count: 0,
  },
  {
    id: 2,
    name: 'Forenza',
    details: 2007,
    quantity: 1,
    category: 'Suzuki',
    count: 0,
  },
  {
    id: 3,
    name: 'Fiero',
    details: 1984,
    quantity: 22,
    category: 'Pontiac',
    count: 0,
  },
  {
    id: 4,
    name: 'Fusion',
    details: 2006,
    quantity: 19,
    category: 'Ford',
    count: 0,
  },
  {
    id: 5,
    name: 'Elantra',
    details: 2006,
    quantity: 28,
    category: 'Hyundai',
    count: 0,
  },
  {
    id: 6,
    name: 'i-350',
    details: 2006,
    quantity: 55,
    category: 'Isuzu',
    count: 0,
  },
  {
    id: 7,
    name: 'RAV4',
    details: 2004,
    quantity: 45,
    category: 'Toyota',
    count: 0,
  },
  {
    id: 8,
    name: 'MX-5',
    details: 2006,
    quantity: 100,
    category: 'Mazda',
    count: 0,
  },
  {
    id: 9,
    name: 'Explorer',
    details: 1999,
    quantity: 66,
    category: 'Ford',
    count: 0,
  },
  {
    id: 10,
    name: 'Spectra',
    details: 2004,
    quantity: 10,
    category: 'Kia',
    count: 0,
  },
  {
    id: 11,
    name: 'E-Class',
    details: 1986,
    quantity: 2,
    category: 'Mercedes',
    count: 0,
  },
  {
    id: 12,
    name: 'GTO',
    details: 1994,
    quantity: 21,
    category: 'Mitsubishi',
    count: 0,
  },
  {
    id: 13,
    name: 'Tucson',
    details: 2005,
    quantity: 65,
    category: 'Hyundai',
    count: 0,
  },
  {
    id: 14,
    name: 'SL-Class',
    details: 1998,
    quantity: 14,
    category: 'Mercedes',
    count: 0,
  },
  {
    id: 15,
    name: 'Town Car',
    details: 1984,
    quantity: 70,
    category: 'Lincoln',
    count: 0,
  },
  {
    id: 16,
    name: 'F150',
    details: 2000,
    quantity: 50,
    category: 'Ford',
    count: 0,
  },
  {
    id: 17,
    name: 'CLK-Class',
    details: 2009,
    quantity: 36,
    category: 'Mercedes',
    count: 0,
  },
  {
    id: 18,
    name: 'Neon',
    details: 2005,
    quantity: 24,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 19,
    name: 'Esprit',
    details: 1996,
    quantity: 40,
    category: 'Lotus',
    count: 0,
  },
  {
    id: 20,
    name: 'H2',
    details: 2007,
    quantity: 91,
    category: 'Hummer',
    count: 0,
  },
  {
    id: 21,
    name: 'Journey',
    details: 2012,
    quantity: 65,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 22,
    name: 'Ram 2500',
    details: 2005,
    quantity: 36,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 23,
    name: '300C',
    details: 2005,
    quantity: 67,
    category: 'Chrysler',
    count: 0,
  },
  {
    id: 24,
    name: 'Echo',
    details: 2004,
    quantity: 85,
    category: 'Toyota',
    count: 0,
  },
  {
    id: 25,
    name: 'Celica',
    details: 2002,
    quantity: 94,
    category: 'Toyota',
    count: 0,
  },
  {
    id: 26,
    name: 'HHR',
    details: 2010,
    quantity: 100,
    category: 'Chevrolet',
    count: 0,
  },
  {
    id: 27,
    name: 'Coupe',
    details: 2005,
    quantity: 44,
    category: 'Maserati',
    count: 0,
  },
  {
    id: 28,
    name: 'Transit Connect',
    details: 2013,
    quantity: 64,
    category: 'Ford',
    count: 0,
  },
  {
    id: 29,
    name: 'Terraza',
    details: 2007,
    quantity: 47,
    category: 'Buick',
    count: 0,
  },
  {
    id: 30,
    name: 'Cougar',
    details: 1995,
    quantity: 23,
    category: 'Mercury',
    count: 0,
  },
  {
    id: 31,
    name: 'Lancer Evolution',
    details: 2011,
    quantity: 98,
    category: 'Mitsubishi',
    count: 0,
  },
  {
    id: 32,
    name: 'XC70',
    details: 2005,
    quantity: 93,
    category: 'Volvo',
    count: 0,
  },
  {
    id: 33,
    name: '1500 Club Coupe',
    details: 1993,
    quantity: 31,
    category: 'GMC',
    count: 0,
  },
  {
    id: 34,
    name: 'Expedition',
    details: 2006,
    quantity: 15,
    category: 'Ford',
    count: 0,
  },
  {
    id: 35,
    name: 'Q',
    details: 1998,
    quantity: 2,
    category: 'Infiniti',
    count: 0,
  },
  {
    id: 36,
    name: 'Pathfinder',
    details: 1999,
    quantity: 72,
    category: 'Nissan',
    count: 0,
  },
  {
    id: 37,
    name: 'Grand Vitara',
    details: 2007,
    quantity: 30,
    category: 'Suzuki',
    count: 0,
  },
  {
    id: 38,
    name: 'Grand Prix',
    details: 1977,
    quantity: 68,
    category: 'Pontiac',
    count: 0,
  },
  {
    id: 39,
    name: 'Sequoia',
    details: 2012,
    quantity: 17,
    category: 'Toyota',
    count: 0,
  },
  {
    id: 40,
    name: 'Sable',
    details: 1993,
    quantity: 81,
    category: 'Mercury',
    count: 0,
  },
  {
    id: 41,
    name: 'Dakota',
    details: 1996,
    quantity: 28,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 42,
    name: 'Transit Connect',
    details: 2011,
    quantity: 25,
    category: 'Ford',
    count: 0,
  },
  {
    id: 43,
    name: 'Esperante',
    details: 2006,
    quantity: 97,
    category: 'Panoz',
    count: 0,
  },
  {
    id: 44,
    name: 'Mighty Max Macro',
    details: 1993,
    quantity: 53,
    category: 'Mitsubishi',
    count: 0,
  },
  {
    id: 45,
    name: 'Expedition',
    details: 1997,
    quantity: 18,
    category: 'Ford',
    count: 0,
  },
  {
    id: 46,
    name: 'Sable',
    details: 1992,
    quantity: 53,
    category: 'Mercury',
    count: 0,
  },
  {
    id: 47,
    name: 'M6',
    details: 2006,
    quantity: 76,
    category: 'BMW',
    count: 0,
  },
  {
    id: 48,
    name: 'Suburban 2500',
    details: 1993,
    quantity: 81,
    category: 'Chevrolet',
    count: 0,
  },
  {
    id: 49,
    name: 'Ram 3500',
    details: 1997,
    quantity: 4,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 50,
    name: 'Escalade ESV',
    details: 2008,
    quantity: 94,
    category: 'Cadillac',
    count: 0,
  },
  {
    id: 51,
    name: 'Xterra',
    details: 2006,
    quantity: 56,
    category: 'Nissan',
    count: 0,
  },
  {
    id: 52,
    name: 'Corvette',
    details: 1997,
    quantity: 83,
    category: 'Chevrolet',
    count: 0,
  },
  {
    id: 53,
    name: 'TL',
    details: 2003,
    quantity: 94,
    category: 'Acura',
    count: 0,
  },
  {
    id: 54,
    name: 'Ram 1500 Club',
    details: 1998,
    quantity: 22,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 55,
    name: 'Grand Prix Turbo',
    details: 1990,
    quantity: 49,
    category: 'Pontiac',
    count: 0,
  },
  {
    id: 56,
    name: 'Escape',
    details: 2000,
    quantity: 42,
    category: 'Ford',
    count: 0,
  },
  {
    id: 57,
    name: 'CR-V',
    details: 2007,
    quantity: 72,
    category: 'Honda',
    count: 0,
  },
  {
    id: 58,
    name: 'Montego',
    details: 2006,
    quantity: 95,
    category: 'Mercury',
    count: 0,
  },
  {
    id: 59,
    name: 'GT500',
    details: 2007,
    quantity: 67,
    category: 'Ford',
    count: 0,
  },
  {
    id: 60,
    name: '929',
    details: 1987,
    quantity: 95,
    category: 'Mazda',
    count: 0,
  },
  {
    id: 61,
    name: 'Diablo',
    details: 1993,
    quantity: 34,
    category: 'Lamborghini',
    count: 0,
  },
  {
    id: 62,
    name: 'Silverado 2500',
    details: 2000,
    quantity: 29,
    category: 'Chevrolet',
    count: 0,
  },
  {
    id: 63,
    name: 'Camry',
    details: 1993,
    quantity: 61,
    category: 'Toyota',
    count: 0,
  },
  {
    id: 64,
    name: 'S-Class',
    details: 2009,
    quantity: 38,
    category: 'Mercedes',
    count: 0,
  },
  {
    id: 65,
    name: 'Yukon XL 1500',
    details: 2007,
    quantity: 81,
    category: 'GMC',
    count: 0,
  },
  {
    id: 66,
    name: 'Sunfire',
    details: 1997,
    quantity: 73,
    category: 'Pontiac',
    count: 0,
  },
  {
    id: 67,
    name: 'Clubman',
    details: 2010,
    quantity: 30,
    category: 'MINI',
    count: 0,
  },
  {
    id: 68,
    name: 'S5',
    details: 2008,
    quantity: 52,
    category: 'Audi',
    count: 0,
  },
  {
    id: 69,
    name: 'Silhouette',
    details: 1999,
    quantity: 100,
    category: 'Oldsmobile',
    count: 0,
  },
  {
    id: 70,
    name: 'F250',
    details: 2008,
    quantity: 63,
    category: 'Ford',
    count: 0,
  },
  {
    id: 71,
    name: 'Outback',
    details: 2001,
    quantity: 34,
    category: 'Subaru',
    count: 0,
  },
  {
    id: 72,
    name: 'Edge',
    details: 2010,
    quantity: 55,
    category: 'Ford',
    count: 0,
  },
  {
    id: 73,
    name: 'MX-5',
    details: 2007,
    quantity: 80,
    category: 'Mazda',
    count: 0,
  },
  {
    id: 74,
    name: 'Caravan',
    details: 2005,
    quantity: 47,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 75,
    name: '3500',
    details: 1995,
    quantity: 19,
    category: 'GMC',
    count: 0,
  },
  {
    id: 76,
    name: 'S-Class',
    details: 2008,
    quantity: 38,
    category: 'Mercedes',
    count: 0,
  },
  {
    id: 77,
    name: 'Fortwo',
    details: 2012,
    quantity: 22,
    category: 'Smart',
    count: 0,
  },
  {
    id: 78,
    name: 'TT',
    details: 2011,
    quantity: 12,
    category: 'Audi',
    count: 0,
  },
  {
    id: 79,
    name: 'Range Rover Sport',
    details: 2008,
    quantity: 16,
    category: 'Land Rover',
    count: 0,
  },
  {
    id: 80,
    name: 'Mazda5',
    details: 2012,
    quantity: 67,
    category: 'Mazda',
    count: 0,
  },
  {
    id: 81,
    name: 'Roadmaster',
    details: 1995,
    quantity: 45,
    category: 'Buick',
    count: 0,
  },
  {
    id: 82,
    name: '626',
    details: 1993,
    quantity: 52,
    category: 'Mazda',
    count: 0,
  },
  {
    id: 83,
    name: 'Fiero',
    details: 1986,
    quantity: 17,
    category: 'Pontiac',
    count: 0,
  },
  {
    id: 84,
    name: 'Bravada',
    details: 2003,
    quantity: 43,
    category: 'Oldsmobile',
    count: 0,
  },
  {
    id: 85,
    name: 'QX56',
    details: 2010,
    quantity: 91,
    category: 'Infiniti',
    count: 0,
  },
  {
    id: 86,
    name: 'Nubira',
    details: 1999,
    quantity: 75,
    category: 'Daewoo',
    count: 0,
  },
  {
    id: 87,
    name: 'Sonata',
    details: 2004,
    quantity: 45,
    category: 'Hyundai',
    count: 0,
  },
  {
    id: 88,
    name: 'Grand Caravan',
    details: 2005,
    quantity: 39,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 89,
    name: 'F250',
    details: 2006,
    quantity: 7,
    category: 'Ford',
    count: 0,
  },
  {
    id: 90,
    name: 'Gran Sport',
    details: 2005,
    quantity: 71,
    category: 'Maserati',
    count: 0,
  },
  {
    id: 91,
    name: 'E150',
    details: 2007,
    quantity: 70,
    category: 'Ford',
    count: 0,
  },
  {
    id: 92,
    name: 'Escalade EXT',
    details: 2007,
    quantity: 70,
    category: 'Cadillac',
    count: 0,
  },
  {
    id: 93,
    name: 'Compass',
    details: 2009,
    quantity: 94,
    category: 'Jeep',
    count: 0,
  },
  {
    id: 94,
    name: 'Ram 1500',
    details: 2007,
    quantity: 53,
    category: 'Dodge',
    count: 0,
  },
  {
    id: 95,
    name: '3 Series',
    details: 1993,
    quantity: 27,
    category: 'BMW',
    count: 0,
  },
  {
    id: 96,
    name: 'RL',
    details: 2003,
    quantity: 9,
    category: 'Acura',
    count: 0,
  },
  {
    id: 97,
    name: 'CL65 AMG',
    details: 2009,
    quantity: 22,
    category: 'Mercedes',
    count: 0,
  },
  {
    id: 98,
    name: 'G',
    details: 2004,
    quantity: 61,
    category: 'Infiniti',
    count: 0,
  },
  {
    id: 99,
    name: 'Tucson',
    details: 2005,
    quantity: 3,
    category: 'Hyundai',
    count: 0,
  },
];
